name: Build and Deploy Docs
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build Runflow References
      run: |
        sudo apt-get install -y graphviz graphviz-dev
        python3 -mpip install -r requirements-dev.txt
        python3 -mpip install -e '.[all]'
        make references

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.GH_PAGES_ACCESS_TOKEN }}
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: docs/.vuepress/dist/
